### ISSUE TITLE
Specify options for image generating tool

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC-viz#1]
1. Slice[=args]
    * with no args - default direction and location 
    * with args : [(<x,y,z>,val),(<x,y,z>,val),....] produces one image for each tuple with slice at plane <x,y,z>=val
 
2. Clip[=args]
    * with no args - default octant, rotation and midpoint
    * with args : [{loc:(x,y,z),octant:(+/-1,+/-1,+/-1),rot:(alpha,beta,gamma)},...] produces one image for each dictionary
    * if only partially defined - default rotation depends on octant
    * default position is center of data (not origin and not center of geometry)

3. Threshold=expr
     * expr = tagname > val | tagname < val | tagname = (min,max)

4. Pseudo = tagname [, log|lin, lower, upper]

5. Contour = tagname

**Comment by leschultz** [comment]
I have added the options desired.
