### ISSUE TITLE
Using pre-defined tag names

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC-viz#15]
Many, if not all, of the tags used in MOAB .h5m files have predefined tag names and sizes included as part of the `pymoab.types` module. We should use those when possible so if they are ever updated or changed in MOAB, those names are updated in the visualization scripts as well. 

An example of this is:
```
cat_tag = mb_core.tag_get_handle("CATEGORY")
```
which would become:
```
cat_tag = mb_core.tag_get_handle(types.CATEGORY_TAG_NAME)
```

**Comment by gonuke** [comment]
Resolved in #17
