### ISSUE TITLE
Comply with community best practices

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC-viz#22]
See [here](https://github.com/svalinn/DAGMC-viz/community) for additions necessary to comply with best practices

**Comment by piperlincoln** [comment]
Opened [PR](https://github.com/CNERG/cnerg.github.com/pull/127) to add Code of Conduct to the CNERG website to be used in all applicable repositories.

**Comment by kkiesling** [comment]
Hmm it looks like PR #26 for the issue template successfully made it on to the list of community best practices as completed. @piperlincoln did that have the correct file naming?

**Comment by piperlincoln** [comment]
@kkiesling I did some research and found that github will only recognize a file explicitly named `ISSUE_TEMPLATE.md` in the root directory, even if multiple issue templates exist in the `.github/` folder. However, it seems multiple other repositories, such as [Ruby on Rails](https://github.com/rails/rails/tree/master/.github), are in this situation as well. Should I create a dummy file to satisfy github that leads to the correct location, or just assume the user will see the clearly marked folder?

**Comment by kkiesling** [comment]
I think you should make it so that the information properly appears when someone tries to make an issue. Right now, there is no information that appears when someone creates an issue and developers/users will likely not dig into folders for these best practices. I think that means it has to be made into a single file in the right location for it to appear.

**Comment by kkiesling** [comment]
Looks like the issues template is now properly recognized in the community best practices as being present (thanks to PR #30), though I am unsure how to actually make that information appear when opening a new issue. As far as I know it only appears [here](https://github.com/svalinn/DAGMC-viz/community). I was thinking it would work like the PR template where information appears when a new PR is opened. But perhaps the issue templates don't work that way?

**Comment by kkiesling** [comment]
Disregard my previous comment. Everything looks to be working as it should. It may have just not fully loaded after merging the PR when I tried it before.

**Comment by piperlincoln** [comment]
This repo now contains a README, Code of Conduct, Contributing Guidelines, License, and PR/Issue Templates and therefore is completely up to date regarding community best practices.
