### ISSUE TITLE
Support tag expansion for VisIt animation

### ISSUE THREAD

**Issue by gonuke** [svalinn/DAGMC-viz#24]
Many results in a DAG-MCNP run produce vectors, especially in terms of multi-group energy fluxes, etc.  Various tools exist (mostly ad-hoc?) to convert between vector tags (a single tag with an array of N values) and scalar tags (N tags each with a single value).

A useful capability would be to generate data files that are named according to VisIt's convention that allows them to be treated as "database" and easily animate/slider bar between them.

This seems like a useful capability to add here.  It might make sense to implement it in a way that can be a standalone tool (overcoming the above mentioned ad-hoc nature) and also be callable from our viz tools.

**Comment by pshriwise** [comment]
@piperlincoln and I talked a little bit about this yesterday. I think it's possible to get any tag we'd want to expand by gathering all tags for any given `MBHEX` element in the mesh. From there, should *any* tag with length > 1 be expanded? I was thinking it might be best to limit the tag data type to `MB_TYPE_DOUBLE` (maybe `MB_TYPE_INTEGER` as well though?)

**Comment by piperlincoln** [comment]
Addressed in PR #28
