### ISSUE TITLE
Make graveyard removal script import-able

### ISSUE THREAD

**Issue by pshriwise** [svalinn/DAGMC-viz#9]
This was requested in #1.

It's very likely that the functionality of this script will be used in other places. Rather than allow it to only operate as a script called from the command line. This module should be made an importable set of code (a module), so that it can be called by modules in this repo without having to setup a command-line call (which is what we do now). 

Guidelines for making the code importable are here: https://kkiesling.github.io/python-novice-gapminder-custom/34-importing/.

**Comment by piperlincoln** [comment]
Addressed in PR #12
